#pragma once

namespace Horizon
{
	enum WindowPollEvent : uint32_t
	{
		POLL_NONE = 0,

		POLL_KEY_PRESSED = 1u << 0,
		POLL_KEY_RELEASED = 1u << 1,
		POLL_KEY_CHAR = 1u << 2,

		POLL_MOUSE_PRESSED = 1u << 3,
		POLL_MOUSE_RELEASED = 1u << 4,
		POLL_MOUSE_MOVED = 1u << 5,
		POLL_MOUSE_SCROLLED = 1u << 6,
		POLL_MOUSE_DOUBLE_CLICK = 1u << 7,

		POLL_GAMEPAD_BUTTON_PRESSED = 1u << 8,
		POLL_GAMEPAD_BUTTON_RELEASED = 1u << 9,
		POLL_GAMEPAD_AXIS_MOVED = 1u << 10,

		POLL_WINDOW_RESIZED = 1u << 11,
		POLL_WINDOW_MOVED = 1u << 12,
		POLL_WINDOW_CLOSED = 1u << 13,
		POLL_WINDOW_FOCUSED = 1u << 14,
		POLL_WINDOW_LOST_FOCUS = 1u << 15,

		POLL_RAW_INPUT_DEVICE_CHANGED = 1u << 16,

		POLL_DRAG_ENTER = 1u << 17,
		POLL_DRAG_LEAVE = 1u << 18,
		POLL_DRAG_DROP = 1u << 19,

		POLL_APP_SET_FOCUS_AS = 1u << 20,
		POLL_MONITOR_CHANGED = 1u << 21,
	};
}