#pragma once

#include <Runtime/Reflection/Type.h>
#include <Runtime/Reflection/TypeDefinitions.h>

namespace Horizon
{
	GENERATE_PRIMITIVE(c8);
	GENERATE_PRIMITIVE(b8);
	GENERATE_PRIMITIVE(u8);
	GENERATE_PRIMITIVE(u16);
	GENERATE_PRIMITIVE(u32);
	GENERATE_PRIMITIVE(u64);
	GENERATE_PRIMITIVE(i16);
	GENERATE_PRIMITIVE(i32);
	GENERATE_PRIMITIVE(i64);
	GENERATE_PRIMITIVE(f32);
	GENERATE_PRIMITIVE(f64);
}